-- AlterTable
ALTER TABLE "User" ALTER COLUMN "birth_date" DROP NOT NULL,
ALTER COLUMN "job" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "summary" DROP NOT NULL;
